### ISSUE TITLE
Improve Cloud Run responsiveness 

### ISSUE THREAD

**Issue by mshidlov** [amplication/blog-client#159]
Change the cloud run deployment to be more responsive.
set the production cloud run:
 1. CPU to 4
 2. memory to 512
 3. min instances to 1
 4. min instances to 5
 5. set the concurrency to 1000
 6. set allocate always-on CPU

**Comment by idanmsela** [comment]
done. 
NOTE: the minimum memory for 4 CPU is 2GB
